// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (
      provider: "google" | "apple" | "microsoft" | "lovable",
      opts?: SignInOptions,
    ): Promise<Awaited<ReturnType<typeof lovableAuth.signInWithOAuth>>> => {
      try {
        console.log("🔵 [lovable.signInWithOAuth] Iniciando autenticación", { provider, opts });
        const result = await lovableAuth.signInWithOAuth(provider, {
          ...opts,
          extraParams: {
            ...opts?.extraParams,
          },
        });

        if (result.redirected || result.error) {
          return result;
        }

        console.log("✅ [lovable.signInWithOAuth] Sesión OAuth establecida", { provider });
        return result;
      } catch (err: unknown) {
        const message = err instanceof Error ? err.message : String(err);
        console.error("❌ [lovable.signInWithOAuth] Error en autenticación", { provider, message });
        throw new Error(`[lovable.signInWithOAuth] ${message}`);
      }
    },
  },
};
